const { IG_USER, IG_PASS, FOLLOW_LIMIT, FOLLOW_PROFILE } = process.env

export default {
	IG_USER: `${IG_USER}`,
	IG_PASS: `${IG_PASS}`,
	FOLLOW_LIMIT: +`${FOLLOW_LIMIT}`,
	FOLLOW_PROFILE: `${FOLLOW_PROFILE}`,
}
